### PR TITLE
[DM-15396] Move to setup.py packaging.

### PR DESCRIPTION
**Pull request by cbanek**
Setup.py and requirements.txt instead of EUPS.
Modified version.py to use the new setuptools_scm plugin.  Setup.cfg
allows for running tests via python setup.py test

### CODE REVIEW

**Comment by cbanek** [comment]
One big problem here is that the unit tests don't seem to pass... well, they do, but the integration tests don't.  This is the last big technical hurdle I think to the stack based container.  Even if we don't run the tests, we can run the service, and imgserv seems to work.

The problem with the tests is this is where there is linkage to the lsst/db repository, which also pulls in things.  We need some of those helper functions, but by taking them in, there are some other problems we draw in.

One other problem is the lack of a imgserv_config.json in the integration/config directory.  I'm guessing these tests are run and pass all the time, so assuming it's my fault.  If something here is broken, let me know.

**Comment by cbanek** [comment]
That is the best news I've had all night.  I don't understand what the test is doing, but if we don't want it, I can nuke that.

There's the test directory where that one lives, and then there's another directory called integration that also has pytest tests in it, which fail for a different reason about not having a metaserv URL.  Are those still useful as well?

**Comment by brianv0** [comment]
I'm pretty sure those are still useful, I _think_ they should pass because I _think_ all the data is in this repo, though maybe @kennywlo needs to take a look at the failures

**Comment by cbanek** [comment]
So when I delete the tests directory, then I seem to be past my problems with dependency hell, which is great.  If we all agree that test is unnecessary, I am happy to take it out.

Then when running the tests in the integration folder, at first run it complains about not finding the imgserv_conf.json in integration/config:

E       FileNotFoundError: [Errno 2] No such file or directory: '/root/dax_imgserv/integration/config/imgserv_conf.json'

When I make a copy over from the other imgserv_conf.json in the repo, I get a different error:
        self.butlerget = ButlerGet(dataRoot, butlerPolicy, butlerKeys, logger)
        self.metaservget = MetaservGet(
>               config["DAX_IMG_META_URL"],
                config["DAX_IMG_META_DB"],
                table, columns, logger)
E       KeyError: 'DAX_IMG_META_URL'

**Comment by cbanek** [comment]
Okay Kenny has filed DM-15694 to track the failing test issue.  Going to take this for now.

**Pull request merged**
